config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 
  namespace :admin do
    get '/', :to => 'dashboard#index'

    resources :dashboard, only: [:index]
    resources :posts
    resources :categories

  end
 # resources :posts
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title,:description,:status
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :image
  # has_rich_text :content

  validates :content,:title, presence: true
  validates :slug, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/category_controller.rb
class Admin::CategoryController < ApplicationController
  before_action only: ["edit","update","destroy"]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect admin_categories_path, notice: "Category crée avec succès"
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect admin_categories_path, notice: "Category mis à jour avec succès"
    end
  end

  def destroy
    if @category.destroy
      redirect admin_categories_path, notice: "Category supprimé avec succès"
    end
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title,:description,:status)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'
  def index
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < BaseController
  layout 'admin'
  before_action :set_post, only: [:destroy,:update,:show,:edit]
  def index
      @posts = Post.all
      # @items = params[:items] || 25
      # @pagy, @posts = pagy(@posts, items: @items)
      # @posts = @posts.decorate
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_posts_path, notice: "Enregistrement effectué avec succès"
    end  

  end

  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to admin_posts_path, notice: "Modification effectuée avec succès"
    end
  end

  def show
    
  end

  def destroy
    if @post.destroy
      redirect_to admin_posts_path, notice: "Suppression effectuée avec succès"
    end
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/category_helper.rb
module Admin::CategoryHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
  def form_field_error(resource, field)
    resource.errors[field].present? ? raw("<div class='help is-danger'>#{resource.errors[field]&.to_sentence}</div>") : ''
  end

  def form_field_error_class(resource, field)
    resource.errors[field].present? ? 'is-danger' : ''
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/category/_form.html.erb
<div class="m-auto">
  <%= form_with model: resource, url: route, method: method do |f| %>
    <div class="columns">
      <div class="column">
        <div class="field">
          <div class="control">
            <% image_url = resource.image.attached? ? rails_representation_url(resource.image.variant(resize_to_limit: [500, 350]).processed, only_path: true) : asset_path('default-image.png') %>
            <% image_name = resource.image.attached? ? resource.image.filename : 'Aucun image' %>
            <div class="form-img-preview" data-controller="file-upload">
              <%= image_tag( image_url, data: {'file-upload-target': "preview"} ) %>
              <%= f.file_field :image, direct_upload: true, class: 'd-none', accept: 'image/jpeg, image/png', data: {'file-upload-target': 'fileInput', action: 'change->file-upload#fileChange'} %>
            </div>
          </div>
        </div>
      </div>
      <div class="column"></div>
    </div>
     <div class="columns">
      <div class="column">
        <div class="field <%= form_field_error_class(resource, 'title') %>">
          <%= f.label :title, 'Titre ', class: 'label' %>
          <div class="control">
            <%= f.text_field :title, class: "input", placeholder: "Titre" %>
          </div>
          <%= form_field_error(resource, 'title') %>
        </div>
       </div>
    </div>
    <div class="columns">
      <div class="column">
        <div class="field <%= form_field_error_class(resource, 'content') %>">
          <%= f.label :content,'Contenu', class: 'label' %>
          <div class="control ">
            <%= f.rich_text_area :content, class: "textarea"%>
          </div>
          <%= form_field_error(resource, 'content') %>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= f.submit 'Créer', class: "button is-primary" %>
    </div>
  <% end %>
</div>  

app/views/admin/category/edit.html.erb
  <%= render 'form', resource: @post, route:admin_post_path, method: "put" %>

app/views/admin/category/index.html.erb
<section class="section is-main-section">

    <div class="card has-table has-mobile-sort-spaced">
      <header class="card-header">
        <p class="card-header-title">
          <span class="icon"><i class="mdi mdi-account-multiple"></i></span>
          Posts
        </p>
        <a href="#" class="card-header-icon">
          <span class="icon"><i class="mdi mdi-reload"></i></span>
        </a>
      </header>
      <div class="card-content">
        <div class="b-table has-pagination">
          <div class="table-wrapper has-mobile-cards">
            <table class="table is-fullwidth is-striped is-hoverable is-sortable is-fullwidth">
              <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Status</th>
                <th>Created</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
            <%if @posts %>  
              <%@posts.each do |post|%>
                <%=render "admin/shared/modal",id: post.id, path:admin_post_path(post) %>

                <tr>
                  <td class="is-image-cell">
                    <div class="image">
                      <img src="https://avatars.dicebear.com/v2/initials/rebecca-bauch.svg" class="is-rounded">
                    </div>
                  </td>
                  <td data-label="Name"><%=post.title%></td>
                  <td data-label="Progress" class="is-progress-cell">
                    <progress max="100" class="progress is-small is-primary" value="79">79</progress>
                  </td>
                  <td data-label="Created">
                    <small class="has-text-grey is-abbr-like" title="Oct 25, 2020"><%=post.created_at%></small>
                  </td>
                  <td class="is-actions-cell">
                    <div class="buttons is-right">
                      <%= link_to  edit_admin_post_path(post),
                        :class => "button is-small is-warning",
                        :method => :get do%>
                        <span class="icon"><i class="mdi mdi-pencil"></i></span>
                      <%end%>
                     
                      <button class="button is-small is-primary" type="button">
                        <span class="icon"><i class="mdi mdi-eye"></i></span>
                      </button>
                      <button class="button is-small is-danger jb-modal" data-target="sample-modal<%=post.id%>" type="button">
                        <span class="icon"><i class="mdi mdi-trash-can"></i></span>
                      </button>
                    </div>
                  </td>
                </tr>
                <%end%>
             <%else%>
              <div>No Posts</div>
             <%end%> 
              </tbody>
            </table>
          </div>
          <div class="notification">
            <div class="level">
              <div class="level-left">
                <div class="level-item">
                  <div class="buttons has-addons">
                    <button type="button" class="button is-active">1</button>
                    <button type="button" class="button">2</button>
                    <button type="button" class="button">3</button>
                  </div>
                </div>
              </div>
              <div class="level-right">
                <div class="level-item">
                  <small>Page 1 of 3</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/admin/category/new.html.erb
  <%= render 'form', resource: @post, route: admin_posts_path, method: "post"%>

app/views/admin/dashboard/index.html.erb
  <%=render "admin/shared/main_section" %>
 

app/views/admin/shared/_aside.html.erb
 <aside class="aside is-placed-left is-expanded">
    <div class="aside-tools">
      <div class="aside-tools-label">
        <span><b>Admin</b> One </span>
      </div>
    </div>
    <div class="menu is-menu-main">
      <p class="menu-label">De General</p>
      <ul class="menu-list">
        <li>
        <%=link_to admin_dashboard_index_path, class:"is-active router-link-active has-icon" do%>
            <span class="icon"><i class="mdi mdi-desktop-mac"></i></span>
            <span class="menu-item-label">Dashboard</span>
         <%end%> 
        </li>
      </ul>
     
      <ul class="menu-list">
        <li>
          <a class="has-icon has-dropdown-icon">
            <span class="icon"><i class="mdi mdi-view-list"></i></span>
            <span class="menu-item-label">Les Posts</span>
            <div class="dropdown-icon">
              <span class="icon"><i class="mdi mdi-plus"></i></span>
            </div>
          </a>
          <ul>
            <li>
               <%=link_to admin_posts_path, class:"has-icon" do%>
                 <span class="menu-item-label">Listes</span>
                <%end%> 
            </li>
            <li>
              <%=link_to new_admin_post_path, class:"has-icon" do%>
                <span class="menu-item-label">Nouveau Post</span>
               <%end%> 
            </li>
          </ul>
        </li>

        <li>
          <%=link_to admin_posts_path, class:"has-icon" do%>
            <span class="icon has-update-mark"><i class="mdi mdi-table"></i></span>
            <span class="menu-item-label">Les Posts</span>
          <%end%> 
        </li>
        <li>
          <a href="forms.html" class="has-icon">
            <span class="icon"><i class="mdi mdi-square-edit-outline"></i></span>
            <span class="menu-item-label">Forms</span>
          </a>
        </li>
        <li>
          <a href="profile.html" class="has-icon">
            <span class="icon"><i class="mdi mdi-account-circle"></i></span>
            <span class="menu-item-label">Profile</span>
          </a>
        </li>
        <li>
          <a class="has-icon has-dropdown-icon">
            <span class="icon"><i class="mdi mdi-view-list"></i></span>
            <span class="menu-item-label">Submenus</span>
            <div class="dropdown-icon">
              <span class="icon"><i class="mdi mdi-plus"></i></span>
            </div>
          </a>
          <ul>
            <li>
              <a href="#void">
                <span>Sub-item One</span>
              </a>
            </li>
            <li>
              <a href="#void">
                <span>Sub-item Two</span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
      <p class="menu-label">About</p>
      <ul class="menu-list">
        <li>
          <a href="https://github.com/vikdiesel/admin-one-bulma-dashboard" target="_blank" class="has-icon">
            <span class="icon"><i class="mdi mdi-github-circle"></i></span>
            <span class="menu-item-label">GitHub</span>
          </a>
        </li>
        <li>
          <a href="https://justboil.me/bulma-admin-template/free-html-dashboard/" class="has-icon">
            <span class="icon"><i class="mdi mdi-help-circle"></i></span>
            <span class="menu-item-label">About</span>
          </a>
        </li>
      </ul>
    </div>
  </aside>

app/views/admin/shared/_footer.html.erb
  <footer class="footer">
    <div class="container-fluid">
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            © 2020, JustBoil.me
          </div>
          <div class="level-item">
            <a href="https://github.com/vikdiesel/admin-one-bulma-dashboard" style="height: 20px">
              <img src="https://img.shields.io/github/v/release/vikdiesel/admin-one-bulma-dashboard?color=%23999">
            </a>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <div class="logo">
              <a href="https://justboil.me"><img src="img/justboil-logo.svg" alt="JustBoil.me"></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

app/views/admin/shared/_hero.html.erb
<section class="hero is-hero-bar">
    <div class="hero-body">
      <div class="level">
        <div class="level-left">
          <div class="level-item"><h1 class="title">
            Dashboard
          </h1></div>
        </div>
        <div class="level-right" style="display: none;">
          <div class="level-item"></div>
        </div>
      </div>
    </div>
  </section>

app/views/admin/shared/_modal.html.erb
<div id="sample-modal<%=id%>" class="modal">
  <div class="modal-background jb-modal-close"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Confirm action</p>
      <button class="delete jb-modal-close" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <p>This will permanently delete <b>Some Object</b></p>
      <p>This is sample modal</p>
    </section>
    <footer class="modal-card-foot">
      <button class="button jb-modal-close">Cancel</button>
       <%= button_to "Delete", path,
      :class => "button is-danger jb-modal-close", :method => :delete %>
    </footer>
  </div>
  <button class="modal-close is-large jb-modal-close" aria-label="close"></button>
</div>

app/views/admin/shared/_navbar.html.erb
<nav id="navbar-main" class="navbar is-fixed-top">
    <div class="navbar-brand">
      <a class="navbar-item is-hidden-desktop jb-aside-mobile-toggle">
        <span class="icon"><i class="mdi mdi-forwardburger mdi-24px"></i></span>
      </a>
      <div class="navbar-item has-control">
        <div class="control"><input placeholder="Search everywhere..." class="input"></div>
      </div>
    </div>
    <div class="navbar-brand is-right">
      <a class="navbar-item is-hidden-desktop jb-navbar-menu-toggle" data-target="navbar-menu">
        <span class="icon"><i class="mdi mdi-dots-vertical"></i></span>
      </a>
    </div>
    <div class="navbar-menu fadeIn animated faster" id="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item has-dropdown has-dropdown-with-icons has-divider is-hoverable">
          <a class="navbar-link is-arrowless">
            <span class="icon"><i class="mdi mdi-menu"></i></span>
            <span>Sample Menu</span>
            <span class="icon">
            <i class="mdi mdi-chevron-down"></i>
          </span>
          </a>
          <div class="navbar-dropdown">
            <a href="profile.html" class="navbar-item">
              <span class="icon"><i class="mdi mdi-account"></i></span>
              <span>My Profile</span>
            </a>
            <a class="navbar-item">
              <span class="icon"><i class="mdi mdi-settings"></i></span>
              <span>Settings</span>
            </a>
            <a class="navbar-item">
              <span class="icon"><i class="mdi mdi-email"></i></span>
              <span>Messages</span>
            </a>
            <hr class="navbar-divider">
           <%= button_to destroy_user_session_path, method: :delete, data: { turbo: "false" },class:"navbar-item" do%>
               <span class="icon"><i class="mdi mdi-logout"></i></span>
              <span>Log Out</span>
           <%end%>
            <a class="navbar-item">
             
            </a>
          </div>
        </div>
        <div class="navbar-item has-dropdown has-dropdown-with-icons has-divider has-user-avatar is-hoverable">
          <a class="navbar-link is-arrowless">
            <div class="is-user-avatar">
              <img src="https://avatars.dicebear.com/v2/initials/john-doe.svg" alt="John Doe">
            </div>
            <div class="is-user-name"><span>John Doe</span></div>
            <span class="icon"><i class="mdi mdi-chevron-down"></i></span>
          </a>
          <div class="navbar-dropdown">
            <a href="profile.html" class="navbar-item">
              <span class="icon"><i class="mdi mdi-account"></i></span>
              <span>My Profile</span>
            </a>
            <a class="navbar-item">
              <span class="icon"><i class="mdi mdi-settings"></i></span>
              <span>Settings</span>
            </a>
            <a class="navbar-item">
              <span class="icon"><i class="mdi mdi-email"></i></span>
              <span>Messages</span>
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
              <span class="icon"><i class="mdi mdi-logout"></i></span>
              <span>Log Out</span>
            </a>
          </div>
        </div>
        <a href="https://justboil.me/bulma-admin-template/free-html-dashboard/" title="About" class="navbar-item has-divider is-desktop-icon-only">
          <span class="icon"><i class="mdi mdi-help-circle-outline"></i></span>
          <span>About</span>
        </a>
        <a title="Log out" class="navbar-item is-desktop-icon-only">
          <span class="icon"><i class="mdi mdi-logout"></i></span>
          <span>Log out</span>
        </a>
      </div>
    </div>
  </nav>

app/views/admin/shared/_title_bar.html.erb
<section class="section is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <ul>
            <li>Admin</li>
            <li>Dashboard</li>
          </ul>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <div class="buttons is-right">
            <a href="https://github.com/vikdiesel/admin-one-bulma-dashboard" target="_blank" class="button is-primary">
              <span class="icon"><i class="mdi mdi-github-circle"></i></span>
              <span>GitHub</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/home/index.html.erb
<%=render "shared/navbar"%>
<%=render "shared/hero"%>

  <div class="container is-max-desktop">
    <%=render "shared/featured"%>
    <%=render "shared/categories"%>
  </div>
<%=render "shared/footer"%> 

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html class="has-aside-left has-aside-mobile-transition has-navbar-fixed-top has-aside-expanded">
  <head>
    <title>Admin One HTML - Bulma Admin Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div id="app" >
    <%=render "admin/shared/navbar" %>
    <%=render "admin/shared/aside" %>
    <%=render "admin/shared/title_bar" %>
    <%=render "admin/shared/hero" %> 
    <%= yield %>
    <%=render "admin/shared/footer" %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scholars1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scholars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <script src="https://kit.fontawesome.com/2828f7885a.js"
    integrity="sha384-WAsFbnLEQcpCk8lM1UTWesAf5rGTCvb2Y+8LvyjAAcxK1c3s5c0L+SYOgxvc6PWG"
    crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com" />  
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_categories.html.erb
 <section class="categories">
      <div class="columns is-multiline">
        <div class="column is-6">
          <div class="category">
            <h1 class="title is-5">
              Billing & Accounts <span>5 articles</span>
            </h1>
            <hr />
            <ul>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                General Billing Overview
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Changing the Account Owner
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Downloading/Printing Your Invoices
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Downloading/Printing Your Invoices
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                What to Do When Your Card is Declined
              </li>
            </ul>
            <h3 class="category-more">View All <i class="far fa-arrow-right icon-padding-left"></i></h3>
          </div>
        </div>
        <div class="column is-6">
          <div class="category">
            <h1 class="title is-5">
              FAQs <span>7 articles</span>
            </h1>
            <hr />
            <ul>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Why Isn't My Custom Profile Data Showing on My Tickets?
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Why Won't My Gmail SMTP Settings Work?
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Is There a Customer Portal My Users Can Log in To?
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                How Do I Export My Contacts, Tickets, Reports?
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                How Do I Search for a Number?
              </li>
            </ul>
            <h3 class="category-more">View All <i class="far fa-arrow-right icon-padding-left"></i></h3>
          </div>
        </div>
        <div class="column is-6">
          <div class="category">
            <h1 class="title is-5">
              Getting Started <span>6 articles</span>
            </h1>
            <hr />
            <ul>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Creating a New Conversation
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Assigning Conversations and Changing Status
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Adding Internal Notes
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Configuring Your Inbox View
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Snoozing a Conversation
              </li>
            </ul>
            <h3 class="category-more">View All <i class="far fa-arrow-right icon-padding-left"></i></h3>
          </div>
        </div>
        <div class="column is-6">
          <div class="category">
            <h1 class="title is-5">
              Users & Groups <span>3 articles</span>
            </h1>
            <hr />
            <ul>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Understanding User Roles
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Creating a Group
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Editing the Role of a User
              </li>
            </ul>
            <h3 class="category-more">View All <i class="far fa-arrow-right icon-padding-left"></i></h3>
          </div>
        </div>
      </div>
    </section>

app/views/shared/_featured.html.erb
<section class="featured">
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <h2 class="subtitle">Featured Articles</h2>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <div class="field has-addons has-addons-centered">
              <div class="control">
                <a class="button is-small" disabled>
                  <i class="far fa-chevron-left"></i>
                </a>
              </div>
              <div class="control">
                <a class="button is-small">
                  <i class="far fa-chevron-right"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="columns">
        <div class="column is-3">
          <article>
            <figure class="image is-5by3">
              <img src="https://i.ibb.co/fq8hSGQ/placeholder-image-368x246.png" />
            </figure>
            <h2 class="subtitle">Creating a Group</h2>
            <span class="tag is-rounded">Users & Groups</span>
          </article>
        </div>
        <div class="column is-3">
          <article>
            <figure class="image is-5by3">
              <img src="https://i.ibb.co/fq8hSGQ/placeholder-image-368x246.png" />
            </figure>
            <h2 class="subtitle">Downloading/Printing Your Invoices</h2>
            <span class="tag is-rounded">Billing & Accounts</span>
          </article>
        </div>
        <div class="column is-3">
          <article>
            <figure class="image is-5by3">
              <img src="https://i.ibb.co/fq8hSGQ/placeholder-image-368x246.png" />
            </figure>
            <h2 class="subtitle">Changing the Account Owner</h2>
            <span class="tag is-rounded">Billing & Accounts</span>
          </article>
        </div>
        <div class="column is-3">
          <article>
            <figure class="image is-5by3">
              <img src="https://i.ibb.co/fq8hSGQ/placeholder-image-368x246.png" />
            </figure>
            <h2 class="subtitle">Adding Internal Notes</h2>
            <span class="tag is-rounded">Billing & Accounts</span>
          </article>
        </div>
      </div>
    </section>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28" />
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-end">
          <a class="navbar-item"> Tag </a>
          <a class="navbar-item"> Author </a>
          <a class="navbar-item"> Style Guide </a>
          <%if signed_in? %>
            <%= link_to "admin",admin_path,class:"navbar-item"%>
          <%else%>
            <%= link_to "Login",new_user_session_path,class:"navbar-item"%>
          <%end%>
        </div>
      </div>
    </div>
  </nav>